### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by santiagobs** [JhonattanReales21/Proyect_DS4A_Team30#7]
@maomiranda30 Hay un error en la linea 67 de get_callbacks.py

```
  File "/home/santiagobs/Documents/Cursos/DS4A/Final Project/Proyect_DS4A_Team30/get_callbacks.py", line 67
    fig5 = px.bar(df_bar, y='canal', x="volumen_pesos", color='canal', orientation="h", hover_name="ciudad_tienda" )
```

**Comment by JoaoRacedo** [comment]
Es un problema de indentation, pero es otra línea además de esa, ya hablé con Mauricio y hicimos el cambio. Falta que lo suba. @maomiranda30 cuando puedas sube los cambios.

**Comment by JoaoRacedo** [comment]
Ya Mauricio arreglo el error así que cerrare el issue.
